class CfgPatches
{
    class PEK_HD_Gear
    {
        author="PEK";
        url="";
        requiredaddons[]=
        {
            "A3_Characters_F",
            "3DMA_WD_Uniform",
            "3DMA_WD_Helmets",
            "3DMA_WD_Vest",
            "3DMA_WD_Backpack"
        };
        requiredVersion=1;
        units[]=
        {
            //Backpacks
            "PEK_HD_NFP_Green_SatL",
            "PEK_HD_NFP_Tan_SatL",
            "PEK_HD_NFP_Multitone_SatL",
            "PEK_HD_NFP_Green_DeltaBag",
            "PEK_HD_NFP_Tan_DeltaBag",
            "PEK_HD_NFP_Multitone_DeltaBag",
            "PEK_HD_NFP_Green_GMRMinimap",
            "PEK_HD_NFP_Tan_GMRMinimap",
            "PEK_HD_NFP_Multitone_GMRMinimap",
            "PEK_HD_NFP_Green_BackPanelBanger",
            "PEK_HD_NFP_Tan_BackPanelBanger",
            "PEK_HD_NFP_Multitone_BackPanelBanger",
            "PEK_HD_NFP_Green_AVSZipOn",
            "PEK_HD_NFP_Tan_AVSZipOn",
            "PEK_HD_NFP_Multitone_AVSZipOn",
            "PEK_HD_NFP_Green_SpiritusBackPanel",
            "PEK_HD_NFP_Tan_SpiritusBackPanel",
            "PEK_HD_NFP_Multitone_SpiritusBackPanel"
        };
        weapons[]=
        {
            //Uniforms
            "PEK_HD_NFP_Green_Patagonia_PadsSleeves",
            "PEK_HD_NFP_Tan_Patagonia_PadsSleeves",
            "PEK_HD_NFP_Multitone_Patagonia_PadsSleeves",
            "PEK_HD_NFP_Green_Patagonia_PadsGlovesSleeves",
            "PEK_HD_NFP_Tan_Patagonia_PadsGlovesSleeves",
            "PEK_HD_NFP_Multitone_Patagonia_PadsGlovesSleeves",
            "PEK_HD_NFP_Green_G3_Uniform_Pads",
            "PEK_HD_NFP_Tan_G3_Uniform_Pads",
            "PEK_HD_NFP_Multitone_G3_Uniform_Pads",
            "PEK_HD_NFP_Green_G3_Uniform_PadsSleeves",
            "PEK_HD_NFP_Tan_G3_Uniform_PadsSleeves",
            "PEK_HD_NFP_Multitone_G3_Uniform_PadsSleeves",
            "PEK_HD_NFP_Green_G3_Uniform_PadsGloves",
            "PEK_HD_NFP_Tan_G3_Uniform_PadsGloves",
            "PEK_HD_NFP_Multitone_G3_Uniform_PadsGloves",
            "PEK_HD_NFP_Green_G3_Uniform_PadsGlovesSleeves",
            "PEK_HD_NFP_Tan_G3_Uniform_PadsGlovesSleeves",
            "PEK_HD_NFP_Multitone_G3_Uniform_PadsGlovesSleeves",

            //Helmets
            "PEK_HD_NFP_Green_Opscore_V1",
            "PEK_HD_NFP_Tan_Opscore_V1",
            "PEK_HD_NFP_Multitone_Opscore_V1",
            "PEK_HD_NFP_Green_Opscore_V2",
            "PEK_HD_NFP_Tan_Opscore_V2",
            "PEK_HD_NFP_Multitone_Opscore_V2",
            "PEK_HD_NFP_Green_Opscore_V3",
            "PEK_HD_NFP_Tan_Opscore_V3",
            "PEK_HD_NFP_Multitone_Opscore_V3",
            "PEK_HD_NFP_Green_Opscore_V4",
            "PEK_HD_NFP_Tan_Opscore_V4",
            "PEK_HD_NFP_Multitone_Opscore_V4",
            "PEK_HD_NFP_Green_Opscore_V5",
            "PEK_HD_NFP_Tan_Opscore_V5",
            "PEK_HD_NFP_Multitone_Opscore_V5"

            //Vests
            "PEK_HD_NFP_Green_Vest_Tyr",
            "PEK_HD_NFP_Tan_Vest_Tyr",
            "PEK_HD_NFP_Multitone_Vest_Tyr",
            "PEK_HD_NFP_Green_AVS_Base",
            "PEK_HD_NFP_Tan_AVS_Base",
            "PEK_HD_NFP_Multitone_AVS_Base",
            "PEK_HD_NFP_Green_AVS_Base_H",
            "PEK_HD_NFP_Tan_AVS_Base_H",
            "PEK_HD_NFP_Multitone_AVS_Base_H",
            "PEK_HD_NFP_Green_AVS_Grenadier",
            "PEK_HD_NFP_Tan_AVS_Grenadier",
            "PEK_HD_NFP_Multitone_AVS_Grenadier",
            "PEK_HD_NFP_Green_AVS_JTAC",
            "PEK_HD_NFP_Tan_AVS_JTAC",
            "PEK_HD_NFP_Multitone_AVS_JTAC",
            "PEK_HD_NFP_Green_AVS_PLLEAD",
            "PEK_HD_NFP_Tan_AVS_PLLEAD",
            "PEK_HD_NFP_Multitone_AVS_PLLEAD",
            "PEK_HD_NFP_Green_AVS_Medic",
            "PEK_HD_NFP_Tan_AVS_Medic",
            "PEK_HD_NFP_Multitone_AVS_Medic",
            "PEK_HD_NFP_Green_AVS_PLRadio",
            "PEK_HD_NFP_Tan_AVS_PLRadio",
            "PEK_HD_NFP_Multitone_AVS_PLRadio",
            "PEK_HD_NFP_Green_AVS_PLSGT",
            "PEK_HD_NFP_Tan_AVS_PLSGT",
            "PEK_HD_NFP_Multitone_AVS_PLSGT",
            "PEK_HD_NFP_Green_AVS_SL",
            "PEK_HD_NFP_Tan_AVS_SL",
            "PEK_HD_NFP_Multitone_AVS_SL",
            "PEK_HD_NFP_Green_AVS_Saw",
            "PEK_HD_NFP_Tan_AVS_Saw",
            "PEK_HD_NFP_Multitone_AVS_Saw",
            "PEK_HD_NFP_Green_AVS_Rifleman_v1",
            "PEK_HD_NFP_Tan_AVS_Rifleman_v1",
            "PEK_HD_NFP_Multitone_AVS_Rifleman_v1",
            "PEK_HD_NFP_Green_AVS_Rifleman_v2",
            "PEK_HD_NFP_Tan_AVS_Rifleman_v2",
            "PEK_HD_NFP_Multitone_AVS_Rifleman_v2",
            "PEK_HD_NFP_Green_AVS_Rifleman_v3",
            "PEK_HD_NFP_Tan_AVS_Rifleman_v3",
            "PEK_HD_NFP_Multitone_AVS_Rifleman_v3",
            "PEK_HD_NFP_Green_AVS_Rifleman_v4",
            "PEK_HD_NFP_Tan_AVS_Rifleman_v4",
            "PEK_HD_NFP_Multitone_AVS_Rifleman_v4",
            "PEK_HD_NFP_Green_AVS_SNOT",
            "PEK_HD_NFP_Tan_AVS_SNOT",
            "PEK_HD_NFP_Multitone_AVS_SNOT"
        };
		magazines[]={};
    };
};

#include "CfgUniform.hpp"
#include "CfgHelmet.hpp"
#include "CfgVest.hpp"
#include "CfgBackpack.hpp"
